# Generated by Django 4.1.1 on 2022-09-28 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('steps', models.TextField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=200)),
                ('quantity', models.FloatField()),
                ('quantity_unit', models.CharField(max_length=10)),
                ('recipes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.recipename')),
            ],
            options={
                'ordering': ['ingredient_name'],
            },
        ),
    ]
